config/routes.rb
Rails.application.routes.draw do
  get 'tweets/new'

  get 'sessions/new'

  get '/auth/:provider/callback', to: 'sessions#create'

  resources :blogs do
    resources :comments
    resources :tweets

    root to: "tweets#index"
  end

  get 'test', to: "static_pages#test"
  root 'static_pages#home'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_api_key
      config.consumer_secret     = Rails.application.secrets.twitter_api_secret
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(params.require(:blog).permit(:title, :body))

    @blog.save
      redirect_to @blog
  end


private
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def test
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = get_tweet
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    @tweet.save
    respond_with(@tweet)
  end

  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/blogs/index.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <div class="navbar-header">
          <a class="navbar-brand" href="#"><h2>Jumblr</h2></a>
      </div>
      <div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Videos</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Music</a></li>
          <li><a href="#">My microblogs</a></li>
        </ul>
      </div>
    </div>
  </nav>
        <% @blogs.each do |blog| %>
        <tr>
      <td><%= blog.title %></td>
      <td><%= blog.body %></td>
        </tr>
        <% end %>
        <%= link_to "Add New Blog", blogs_path, class: 'btn btn-lg btn-default'%>
      </div>

      <div class="form">
        <textarea name="message" rows="10" cols="30" style="background-color:#888888;">some text here some text here some text here </textarea>
        <textarea name="message" rows="10" cols="30" style="background-color:#888888;">some text here some text here some text here </textarea>

  </div>

app/views/blogs/new.html.erb
<h1> New microblog</h1>

<%= form_for :blog, url: blogs_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jumbler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">
          Tweeter
        </a>
        <% if current_user %>
        <p class= "navbar-text navbar-right">Signed in as <%= current_user.name %></p>
    <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/home.html.erb
<h1>Microblog time</h1>
<p>more to develop later</p>

<%= link_to "test", root_path, class: 'btn btn-lg btn-warning' %>

app/views/static_pages/test.html.erb
<h1>StaticPages#test</h1>
<p>Find me in app/views/static_pages/test.html.erb</p>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>